# Generated by Django 4.0.1 on 2022-01-28 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
            ],
            options={
                'verbose_name': 'Oпрашивающий',
                'verbose_name_plural': 'Oпрашивающий',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_question', models.CharField(max_length=500)),
                ('sub_question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medhub.interrogator')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls_responder', to='medhub.poll')),
            ],
            options={
                'verbose_name': 'Oтветчики',
                'verbose_name_plural': 'Oтветчики',
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(related_name='poll_questions', to='medhub.Question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_answer', models.CharField(max_length=255)),
                ('sub_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('interrogator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medhub.interrogator')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medhub.poll')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medhub.responder')),
            ],
        ),
    ]
